### ISSUE TITLE
IE 11 Support

### ISSUE THREAD

**Issue by nikolowry** [systemjs/systemjs-transform-babel#4]
Finally took the time to upgrade legacy `systemjs v.0.21.4`, but I can't get IE 11 working -- it's throwing the following error:
```
SCRIPT1010: Expected Identifier
babel-transform (1,392099)
```

And the debugger breaks at the spread syntax args (`function(...e)`):
```javascript 
Object.defineProperty(t,"__esModule",{value:!0}),t.arrayExpression=t.ArrayExpression=function(...e){return(0,i.default)("ArrayExpression",...e)} 
```

From casually scrolling the minified file in the debugger, it seems like that's the first usage of spread syntax. I'm using Rollup for production builds and it runs fine when compiled (and not using SystemJS)

![Screenshot from 2019-10-22 14-17-42](https://user-images.githubusercontent.com/597310/67318950-3b830180-f4da-11e9-8fcc-d6213ddcadbe.png)

**Comment by internettrans** [comment]
Pull requests accepted on this

**Comment by guybedford** [comment]
The issue here is that Babel itself doesn't support IE11. You could try applying Babel to Babel....

**Comment by nikolowry** [comment]
@guybedford would that require `babel-loader` and `core-js` for polyfilling? Just checking as I haven't used Webpack in years (original reason I switched to SystemJS was due to loathing the config hell).
